branch-defaults:
  default:
    environment: parseserver-bsmcf-env
  master:
    environment: parseserver-bsmcf-env
    group_suffix: null
global:
  application_name: titanium
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2016.03 v2.1.1 running Node.js
  default_region: us-east-1
  profile: eb-cli2
  sc: git
